### ISSUE TITLE
Consistency with the built-in Zotero system

### ISSUE THREAD

**Issue by rosslaird** [hkgnp/logseq-readwise-plugin#9]
An entry from the built-in Zotero connection creates properties like so:

    tags:: [[bias]], [[research]], [[uncertainty]]
    date:: 2020
    extra:: OCLC: 1061820225
    isbn:: 978-0-425-28464-3
    title:: @Skin in the game: hidden asymmetries in daily life
    item-type:: [[book]]
    original-title:: Skin in the game: hidden asymmetries in daily life
    language:: English
    short-title:: Skin in the game
    authors:: [[Nassim Nicholas Taleb]]
    library-catalog:: Open WorldCat
    links:: [Local library](zotero://select/library/items/JG44VHNX), [Web library].
    (https://www.zotero.org/users/5457446/items/JG44VHNX)

For a Readwise quotation from the publication above, the Readwise plugin creates properties like so:

    retrieved:: [[Jan 15th, 2022]], :04:3
    author:: [[Nassim Nicholas Taleb]]
    category:: [[books]]
    source:: [[kindle]]
    tags:: [[uncertainty]], [[bias]], [[research]]

The two sets of properties refer to the same thing in two different ways: in this case, [[book]] vs. [[books]] (there may be other such instances in other types of references). The category (aka item-type) entries are not aligned, with the result that two pages are created (book and books) for the same type of thing.

Furthermore, each Zotero reference creates a separate page (with title of the form `@Skin in the game: hidden asymmetries in daily life`, and the Readwise plugin creates its own page of the form `Skin in the Game (Readwise)`. It would be good to have a single unified page for each publication, showing both the Zotero citation and its accompanying Readwise quotations — instead of two different pages for the same publication. This might be tough to do, as some integration with the Zotero plugin would (probably) be required.

**Comment by benjypng** [comment]
Thanks for taking the time to write out this suggestion. As you correctly mention, these are two separate plugins, hence they function quite differently, e.g. in how they parse titles. It will be difficult to combine both natively into 1 plugin since I also do not have control on how Readwise provides the data in their plugin, e.g. `books` was given by them, rather than by the plugin.

An alternative would be to use queries to manually link them together (query for both book and books), but I understand that this is still not as automated.

Apologies about this!

**Comment by rosslaird** [comment]
That makes sense. Thanks for explaining the situation and for the great plugin.

**Comment by benjypng** [comment]
Most welcome!
